projects:
  app:
    schemaPath: 'src/schema.graphql'
    extensions:
      endpoints:
        default: 'http://localhost:8880'
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: prisma.yml
